Imprv/upgrade helm v3 in release workflow
weseek/helm-charts pull request #20
Opened 2021-05-21 11:56 UTC by userlocalhost

This PR runs `misc/exec-helm-test.sh` with Helm3 in GitHub Actions.
<img width="1430" alt="スクリーンショット 2021-05-21 20 45 57" src="https://user-images.githubusercontent.com/469934/119133477-e96bde80-ba76-11eb-8dd5-08292d3b32b8.png">

This has following changes.

- Change of GitHub Action's configuration file to run lint_and_install job when PR is created and run release job only when master branch is updated.
- Change version of Helm to run in the GitHub Action's runtime environment from v2.16.3 to v3.5.4 which is the latest version at present.

2021-06-03 21:07 UTC, skomma approved these changes
Thank you for a pull request.
We will merge this.

2021-06-03 21:18 UTC, skomma requested changes
Sorry, will you fix this?

2021-06-03 21:18 UTC, skomma commented on .github/scripts/install-helm.sh
>  if [ -f "${INSTALL_DIR}/helm" ]; then
`--client` option in `helm version` commadn is not needed anymore.

2021-06-03 21:22 UTC, skomma commented
The first time, CI job outputs Helm v3.6.0 installed.
Where comes Helm v3.6.0 from?

https://github.com/weseek/helm-charts/pull/20/checks?check_run_id=2740944787#step:4:11

2021-06-04 02:50 UTC, userlocalhost commented
Thank you for your review. I understood below.

* remove unnecessary statement that shows helm version in the `install-helm.sh`
* check why helm 3.6.0 is installed at first unintentionally and prevent it

2023-01-01 16:41 UTC, merged