Imprv/auto publish charts in gh pages branch
weseek/helm-charts pull request #7
Opened 2020-03-15 04:01 UTC by ryu-sato

This PR is implementation of #2.

All todos have been completed.

- [x] prepare GitHub Actions workflow
- [x] adjust documentation of charts
    - [x] Add "helm repo add" instruction.

# Features

* Save helm packages to `gh-pages` branch (If you wish to change branch name, you can change by `GH_PAGES_BRANCH`)
* Lint all charts where under `./charts` directory
* If you need, Install all charts where under `./charts` and run test of each chart (default off)
    * This feature spends few minutes

# Prerequired

Create orphan branch and configure GitHub Pages.  
(follow https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site)

# Confirmed to follows

* When update chart version, new version chart is added to helm repository
* When add new chart in GitHub repository, successfully new chart is added to helm repository
* When chart has some syntax errors, action was failed ([ref](https://github.com/ryu-sato/helm-charts/actions/runs/55760719))
* When chart cannot install successfully, action was failed ([ref](https://github.com/ryu-sato/helm-charts/runs/508176942?check_suite_focus=true#step:6:880))
    * This feature is optional

# Note

I would recommend not to use `helm/chart-testing-action` and `helm/chart-releaser-action` now, because these actions have some bugs in checking charts.

* https://github.com/helm/chart-testing/issues/169
* https://github.com/helm/chart-testing-action/issues/20
* https://github.com/helm/chart-releaser-action/issues/13

2020-03-15 19:12 UTC, yuki-takei commented on .github/workflows/release.yaml
> +          helm version --server
一つ一つのステップのスクリプトが多いので、`.sh` ファイルに切り出した方が見通しはいいんじゃないかなあという所感。

2020-03-15 19:12 UTC, yuki-takei commented on .github/workflows/release.yaml
> +            (helm install --timeout 600 --debug --dep-up --wait -n ${CHART} ${CHART} \
timeout も env にしてはどうか

2020-03-16 15:52 UTC, ryu-sato commented on .github/workflows/release.yaml
> +          helm version --server
シェルスクリプトに切り出しました。

2020-03-16 15:53 UTC, ryu-sato commented on .github/workflows/release.yaml
> +            (helm install --timeout 600 --debug --dep-up --wait -n ${CHART} ${CHART} \
env にしました。

2020-03-17 08:45 UTC, ryu-sato commented
> When chart has some syntax errors, action was failed (ref)

Corrected URL of above reference.

2020-03-24 11:10 UTC, yuki-takei commented
scripts の中身って手で打つことは全く想定してない？
マニュアルでも使うんだったら .github の外に出した方がいいんじゃないかと思う。

そうでなければ大筋問題ないと思います。整然としてるし。

2020-03-24 11:17 UTC, ryu-sato commented
> scripts の中身って手で打つことは全く想定してない？
> マニュアルでも使うんだったら .github の外に出した方がいいんじゃないかと思う。

手で打つことは想定してませんでした。
使えそうなものがないか有れば .github の外に出してみます。

2020-03-28 09:56 UTC, ryu-sato commented
> scripts の中身って手で打つことは全く想定してない？
> マニュアルでも使うんだったら .github の外に出した方がいいんじゃないかと思う。

exec-helm-test.sh はマニュアルでも使えそうだったので misc に移動させ、コマンド単体で使えるように以下の改善を行いました。

* コマンドオプションを用意
* kind を既に使っている場合を考慮
    * コマンドインストールをスキップ
    * クラスタ名が競合しにくいようランダムな名前を生成
* シェル終了時に作業リソースを削除
    * インストールディレクトリを削除
    * クラスタを削除

2020-03-28 15:01 UTC, skomma requested changes

2020-03-28 15:01 UTC, skomma commented on .github/scripts/install-helm.sh
> +HELM_VERSION="${HELM_VERSION:-2.16.3}"
別 PR で全然いいんだけど、helm3 でもテストしたいお気持ち。

2020-03-28 15:01 UTC, skomma commented on .github/scripts/update-repository.sh
> +# ================================================================================
他のスクリプトもそうだけど、参考にしたスクリプトがあるなら、その URL を書いておいてほしいかも。

2020-03-28 15:01 UTC, skomma commented on .github/scripts/update-repository.sh
> +# Update helm repository that published by GitHub Page
この場合、that は不要じゃない？
それか `Upgrade the helm repository on GitHub Pages` か。

2020-03-28 15:01 UTC, skomma commented on .github/scripts/update-repository.sh
> +#   SRC_CHART_PATH_BASE ... base path where charts are (default: "charts")
charts 言ってるのに環境変数名は `CHART` になってしまっている。

2020-03-28 15:01 UTC, skomma commented on misc/exec-helm-test.sh
> +  # Create k8s cluster using `kind` to test installation ability
ability 不要？
`to test chart installation`

2020-03-28 15:01 UTC, skomma commented on misc/exec-helm-test.sh
> +# Install helm into tempolary k8s cluster and execute helm test
`tempolary` -> `temporary`
だが、kind と言ってしまっていいような気がするな。
あと、クラスタにインストールするのは tiller であって、それも helm3 では必要なくなるので、
```
Create kind cluster and execute "helm test"
```
の方がすっきりするかも？

2020-03-28 15:01 UTC, skomma commented on misc/exec-helm-test.sh
> +# <Prerequired>
`Prerequired` ってあんまり見ない表現かな。
`What you need to execute` とかがわかりやすい？
https://www.deepl.com/translator#ja/en/%E5%AE%9F%E8%A1%8C%E3%81%AB%E5%BF%85%E8%A6%81%E3%81%AA%E3%82%82%E3%81%AE

2020-03-28 15:01 UTC, skomma commented on misc/exec-helm-test.sh
> +  # Install `kind` if doesn't exist
if **it** doesn't exist. かな？

2020-03-29 12:55 UTC, ryu-sato commented on .github/scripts/update-repository.sh
> +# ================================================================================
参考にしたもののURLを書いておきます。

2020-03-29 12:56 UTC, ryu-sato commented on .github/scripts/update-repository.sh
> +# Update helm repository that published by GitHub Page
> Upgrade the helm repository on GitHub Pages

にします。

2020-03-29 12:58 UTC, ryu-sato commented on misc/exec-helm-test.sh
> +  # Create k8s cluster using `kind` to test installation ability
ability 消しておきます。

2020-03-29 13:00 UTC, ryu-sato commented on misc/exec-helm-test.sh
> +# Install helm into tempolary k8s cluster and execute helm test
この文では `helm` は `chart` を指してしまってますね。
正しくはないので修正します。

2020-03-29 13:06 UTC, ryu-sato commented on misc/exec-helm-test.sh
> +# <Prerequired>
`Prerequisites` と書いた(書きたかった)記憶があるのですが、なぜ `Prerequired` と書いたのが覚えてないです...

`What you need to execute` にしておきます。

2020-03-29 13:07 UTC, ryu-sato commented on misc/exec-helm-test.sh
> +  # Install `kind` if doesn't exist
修正します。

2020-03-29 13:12 UTC, ryu-sato commented on .github/scripts/install-helm.sh
> +HELM_VERSION="${HELM_VERSION:-2.16.3}"
Issue を作っておいてください。

2020-03-29 13:17 UTC, ryu-sato commented on .github/scripts/update-repository.sh
> +#   SRC_CHART_PATH_BASE ... base path where charts are (default: "charts")
`SRC_CHARTS_PATH_BASE` にしておきます。

2020-04-02 04:45 UTC, skomma commented on .github/scripts/install-helm.sh
> +HELM_VERSION="${HELM_VERSION:-2.16.3}"
https://github.com/weseek/helm-charts/issues/8
作っておいた。

2020-04-02 04:47 UTC, skomma commented on .github/scripts/install-helm.sh
> +#   HELM_VERSION ... Helm version which will be installed. (default: "0.7.0")
default が全然違う。

2020-04-02 04:47 UTC, skomma commented on .github/scripts/update-repository.sh
> +# Update helm repository that published by GitHub Page
言っといてゴメン、Upgrade じゃなくて Update だったわ…

2020-04-02 04:49 UTC, skomma commented on misc/exec-helm-test.sh
> +# Install helm into tempolary k8s cluster and execute helm test
> `tempolary` -> `temporary`

無視されてる…

2020-04-02 14:40 UTC, ryu-sato commented on .github/scripts/install-helm.sh
> +#   HELM_VERSION ... Helm version which will be installed. (default: "0.7.0")
気が付きませんでした。修正します。

2020-04-02 14:40 UTC, ryu-sato commented on misc/exec-helm-test.sh
> +# Install helm into tempolary k8s cluster and execute helm test
ごめん、これは無視したわけではなく、Create kind cluster and execute "helm test" へ修正したつもりだったけど push されてなかったみたいです。

2020-04-02 14:41 UTC, ryu-sato commented on .github/scripts/update-repository.sh
> +# Update helm repository that published by GitHub Page
Update にしておきます。

2020-04-02 18:30 UTC, skomma requested changes
ラスト一点！ :pray:

2020-04-02 18:30 UTC, skomma commented on .github/workflows/release.yaml
> +      - name: Update helm repository that is published by GitHub Page
ここも文言を揃えたほうがよさげ。

2020-04-03 01:05 UTC, ryu-sato commented on .github/workflows/release.yaml
> +      - name: Update helm repository that is published by GitHub Page
なるほど、確かにそうでした。
スクリプトの中身と揃えます。

2020-04-04 05:07 UTC, skomma approved these changes

2020-04-04 05:08 UTC, merged